name: Docker Image CI

on:
  push:
    branches: ['main']

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Get short commit SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: 'Authenticate to GCP via Workload Identity Federation'
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          create_credentials_file: 'true'
          project_id: 'vernal-mantra-665'
          workload_identity_provider: '${{ vars.WIF_PROVIDER }}'

      - uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 416.0.0'

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: europe-west2-docker.pkg.dev
          username: oauth2accesstoken
          password: '${{ steps.auth.outputs.auth_token }}'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push the Docker image
        run: |
          docker buildx build \
            --build-arg NEXT_PUBLIC_PAYPAL_CLIENT_ID \
            -t europe-west2-docker.pkg.dev/vernal-mantra-665/eu/ticketing-app:${{ github.ref_name }} \
            -t europe-west2-docker.pkg.dev/vernal-mantra-665/eu/ticketing-app:${{ env.SHORT_SHA }} \
            --push --cache-to type=gha,mode=max --cache-from type=gha .
        env:
          NEXT_PUBLIC_PAYPAL_CLIENT_ID: AWpkJNdY9f7V_3OaLqMa0JkcuxEnsny8WEbXp3nDVU9JEJPeaMCzNA3oPzbkY4kYu-UTYEeOxk2eSOdj
